### ISSUE TITLE
[BO] : CRUD Relations

### ISSUE THREAD

**Issue by Akayreddine** [CUBEb4g1/Projet-CUBE-Web#33]
Créer un CRUD basique + views en BO pour gérer les relations et les catégories.

**Comment by toolib-kent** [comment]
In computer programming, create, read, update, and delete[1] (CRUD) are the four basic functions of persistent storage.[2] Alternate words are sometimes used when defining the four basic functions of CRUD, such as retrieve instead of read, modify instead of update, or destroy instead of delete. CRUD is also sometimes used to describe user interface conventions that facilitate viewing, searching, and changing information, often using computer-based forms and reports

Didn't know that...
Working on it

**Comment by toolib-kent** [comment]
@Akayreddine @Kayreddine 
De quels champs avons nous besoin dans le CRUD ? 
Et qu'entends tu par views en "BO" ?

**Comment by toolib-kent** [comment]
Créer les routes dans web.php (tu peux t'inspirer de la branche de Nathan, je l'ai fix la semaine dernière, il y a des chemins qui vont seulement en backoffice)
[15:08]
à chaque élément du CRUD tu auras une fonction. Chaque fonction a une route
[15:08]
Et donc chaque fonction fait un traitement puis renvoie une view
